#!/bin/python3

import math
import os
import random
import re
import sys
from datetime import datetime, timedelta, timezone

# Complete the time_delta function below.
def time_delta(t1, t2):
    
    def parse_timestamp(timestamp):
        
        dt_str, offset_str = timestamp[:-5], timestamp[-5:]
        
        dt = datetime.strptime(dt_str.strip(), "%a %d %b %Y %H:%M:%S")
        
        offset_hours = int(offset_str[:3])
        offset_minutes = int(offset_str[0] + offset_str[3:])
        
        offset = timezone(timedelta(hours=offset_hours, minutes=offset_minutes))
        return dt.replace(tzinfo=offset)
    
    dt1 = parse_timestamp(t1)
    dt2 = parse_timestamp(t2)
    
    d = abs((dt1 - dt2).total_seconds())
    
    return str(int(d))
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta + '\n')

    fptr.close()
